export async function POST(request) {
  const supabaseUrl = process.env.SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    return new Response(JSON.stringify({ error: 'Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY' }), { status: 500 });
  }

  const body = await request.json();
  const { deal_id, buyer_name, seller_name, region, amount_total, lc_reference_number } = body || {};

  if (!deal_id || !buyer_name || !seller_name) {
    return new Response(JSON.stringify({ error: 'deal_id, buyer_name, seller_name required' }), { status: 400 });
  }

  // Fetch deal details from Supabase
  const dealResp = await fetch(`${supabaseUrl}/rest/v1/green_acc_deals?id=eq.${deal_id}&select=*`, {
    headers: {
      'Content-Type': 'application/json',
      apikey: serviceRoleKey,
      Authorization: `Bearer ${serviceRoleKey}`
    }
  });
  const deals = await dealResp.json();
  if (!Array.isArray(deals) || deals.length === 0) {
    return new Response(JSON.stringify({ error: 'Deal not found' }), { status: 404 });
  }

  const deal = deals[0];

  // AI agents generate professional press release
  // Mock generation: combine buyer/seller names and region into a press release template
  const pressRelease = `FOR IMMEDIATE RELEASE

${buyer_name} and ${seller_name} Announce Strategic Partnership via Greens ACC

${region || 'Global'} — ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

${buyer_name} and ${seller_name} are pleased to announce the successful completion of a strategic trade partnership facilitated through the Greens ACC platform, powered by advanced AI verification and secure escrow mechanisms.

This partnership demonstrates the companies' commitment to transparent, efficient global commerce. The transaction was secured through a comprehensive multi-step verification process, including legal compliance review, financial verification, and automated risk assessment by Greens ACC's three independent AI agents.

"This collaboration exemplifies the future of B2B trade — fast, secure, and transparent," said a representative of ${buyer_name}. "The Greens ACC platform provided the confidence and efficiency we needed to execute this deal seamlessly."

The partnership is now live and both parties look forward to delivering value to their respective stakeholders and markets.

About the Partnership: This transaction was executed in the ${region} region and represents a significant milestone in secure international commerce.

###

For more information about Greens ACC, visit www.greensacc.com

Media Inquiries:
Greens ACC Communications
press@greensacc.com
+1-XXX-XXX-XXXX

---
This press release was auto-generated by Greens ACC's AI verification engine. All parties involved are bound by standard confidentiality and non-disclosure agreements regarding transaction specifics.`;

  // Generate deal announcement record
  const announcementPayload = {
    deal_id,
    press_release: pressRelease,
    social_posts: {
      linkedin: `Exciting news! ${buyer_name} and ${seller_name} have successfully completed a major trade partnership on the Greens ACC platform. Secured by AI verification and transparent escrow. 🌍 #Greens ACC #B2BTrade #SupplyChain`,
      twitter: `📢 ${buyer_name} + ${seller_name} partnership complete on Greens ACC! Transparent, secure, AI-verified trade. #Greens ACC #logistics #B2B`,
      corporate: `${buyer_name} and ${seller_name} announce successful partnership via Greens ACC DEX. Powered by AI agents and secure escrow. Learn more: greensacc.com`
    },
    syndication_status: 'draft',
    created_at: new Date().toISOString()
  };

  // Insert into deal_announcements
  const insertResp = await fetch(`${supabaseUrl}/rest/v1/deal_announcements`, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      apikey: serviceRoleKey,
      Authorization: `Bearer ${serviceRoleKey}`,
      Prefer: 'return=representation'
    },
    body: JSON.stringify(announcementPayload)
  });

  const announcement = await insertResp.json();
  if (!insertResp.ok) {
    return new Response(JSON.stringify({ error: 'Failed to create announcement', details: announcement }), { status: insertResp.status });
  }

  const created = Array.isArray(announcement) ? announcement[0] : announcement;

  return new Response(JSON.stringify({ message: 'press release generated', announcement: created }), { status: 200 });
}
