export const AGENT_REGISTRY = [
  {
    id: 'green_container_agent',
    name: 'Green Container Agent',
    purpose: 'Manage and retrieve container metadata',
    allowedDomains: ['identity', 'document'],
    maxActions: 10,
    requiresConsent: true,
  },
  {
    id: 'trust_agent',
    name: 'Trust Agent',
    purpose: 'Evaluate behavioral trust signals',
    allowedDomains: [],
    maxActions: 5,
    requiresConsent: false,
  },
  {
    id: 'security_agent',
    name: 'Security Agent',
    purpose: 'Monitor and respond to security threats',
    allowedDomains: [],
    maxActions: 3,
    requiresConsent: false,
  },
  {
    id: 'integrity_agent',
    name: 'Integrity Agent',
    purpose: 'Verify document and data integrity',
    allowedDomains: ['document'],
    maxActions: 5,
    requiresConsent: true,
  },
  {
    id: 'aegis_repair_agent',
    name: 'Aegis Repair Agent',
    purpose: 'Execute pre-approved system repairs',
    allowedDomains: [],
    maxActions: 2,
    requiresConsent: false,
  },
  {
    id: 'travel_agent',
    name: 'Travel Agent',
    purpose: 'Prepare travel itineraries and booking information',
    allowedDomains: ['travel_profile', 'identity'],
    maxActions: 10,
    requiresConsent: true,
  },
  {
    id: 'form_assistant',
    name: 'Form Assistant',
    purpose: 'Identify and prepare official form data',
    allowedDomains: ['identity', 'document'],
    maxActions: 8,
    requiresConsent: true,
  },
  {
    id: 'document_agent',
    name: 'Document Agent',
    purpose: 'Retrieve and prepare document previews',
    allowedDomains: ['document'],
    maxActions: 10,
    requiresConsent: true,
  },
  {
    id: 'payment_agent',
    name: 'Payment Agent',
    purpose: 'Prepare payment authorizations using stored tokens',
    allowedDomains: ['financial_authorization'],
    maxActions: 3,
    requiresConsent: true,
  },
  {
    id: 'grocery_agent',
    name: 'Grocery Agent',
    purpose: 'Prepare household shopping lists',
    allowedDomains: ['household_profile'],
    maxActions: 5,
    requiresConsent: true,
  },
  {
    id: 'bill_agent',
    name: 'Bill Agent',
    purpose: 'List and prepare bill payment authorizations',
    allowedDomains: ['financial_authorization'],
    maxActions: 5,
    requiresConsent: true,
  },
  {
    id: 'renewal_agent',
    name: 'Renewal Agent',
    purpose: 'Identify and prepare renewal forms',
    allowedDomains: ['identity', 'document'],
    maxActions: 5,
    requiresConsent: true,
  },
  {
    id: 'audit_agent',
    name: 'Audit Agent',
    purpose: 'Generate audit reports from access logs',
    allowedDomains: [],
    maxActions: 3,
    requiresConsent: false,
  },
  {
    id: 'reporting_agent',
    name: 'Reporting Agent',
    purpose: 'Generate system and compliance reports',
    allowedDomains: [],
    maxActions: 3,
    requiresConsent: false,
  },
];
